# CodeRabbit Configuration for neXed MVP
# This file configures AI-powered code reviews for the project

# Project Information
project:
  name: "neXed MVP"
  description: "Visa compliance management platform for international students"
  type: "web-application"
  tech_stack: ["React", "TypeScript", "Vite", "Supabase", "Tailwind CSS"]

# Review Configuration
review:
  # Enable AI-powered code reviews
  enabled: true
  
  # Review scope
  scope:
    # Include these file types in reviews
    include:
      - "src/**/*.{ts,tsx,js,jsx}"
      - "src/**/*.{css,scss}"
      - "*.{json,yaml,yml}"
      - "*.{md,txt}"
    
    # Exclude these files/directories
    exclude:
      - "node_modules/**"
      - "dist/**"
      - "build/**"
      - "*.min.js"
      - "*.bundle.js"
      - "coverage/**"
      - "*.test.{ts,tsx,js,jsx}"
      - "*.spec.{ts,tsx,js,jsx}"

# Quality Standards
quality:
  # Code quality checks
  checks:
    - "security"
    - "performance"
    - "accessibility"
    - "best-practices"
    - "type-safety"
    - "react-patterns"
  
  # Severity levels to flag
  severity_levels:
    - "error"
    - "warning"
    - "suggestion"

# Security Configuration
security:
  # Enable security scanning
  enabled: true
  
  # Security checks
  checks:
    - "sql-injection"
    - "xss"
    - "authentication"
    - "authorization"
    - "data-exposure"
    - "dependency-vulnerabilities"

# Performance Configuration
performance:
  # Enable performance analysis
  enabled: true
  
  # Performance checks
  checks:
    - "bundle-size"
    - "render-performance"
    - "memory-leaks"
    - "api-optimization"

# Accessibility Configuration
accessibility:
  # Enable accessibility checks
  enabled: true
  
  # WCAG compliance level
  compliance_level: "AA"
  
  # Accessibility checks
  checks:
    - "semantic-html"
    - "aria-labels"
    - "color-contrast"
    - "keyboard-navigation"
    - "screen-reader"

# React/TypeScript Specific
react:
  # React-specific checks
  checks:
    - "hooks-rules"
    - "component-structure"
    - "state-management"
    - "prop-types"
    - "memoization"

typescript:
  # TypeScript-specific checks
  checks:
    - "type-safety"
    - "interface-design"
    - "generic-usage"
    - "strict-mode"

# Custom Rules for neXed MVP
custom_rules:
  # MVP-specific rules
  mvp_features:
    - "feature-flags-implemented"
    - "environment-configuration"
    - "supabase-integration"
    - "responsive-design"
  
  # Business logic rules
  business_logic:
    - "visa-compliance-logic"
    - "user-authentication"
    - "document-management"
    - "data-privacy"

# Review Templates
templates:
  # PR review template
  pr_review:
    sections:
      - "Security Analysis"
      - "Performance Impact"
      - "Code Quality"
      - "Accessibility"
      - "MVP Feature Compliance"
      - "Testing Coverage"
      - "Documentation"

# Auto-fix Configuration
auto_fix:
  # Enable automatic fixes for simple issues
  enabled: true
  
  # Types of issues that can be auto-fixed
  fixable_issues:
    - "formatting"
    - "imports"
    - "simple-type-errors"
    - "unused-variables"
    - "simple-accessibility"

# Integration Settings
integrations:
  # GitHub integration
  github:
    enabled: true
    # Auto-comment on PRs
    auto_comment: true
    # Create review comments
    review_comments: true
  
  # Slack integration (if needed)
  slack:
    enabled: false

# Notification Settings
notifications:
  # Email notifications
  email:
    enabled: true
    recipients: []  # Add email addresses as needed
  
  # In-app notifications
  in_app:
    enabled: true

# Advanced Settings
advanced:
  # Review depth
  review_depth: "comprehensive"
  
  # Context window
  context_window: "large"
  
  # Custom prompts
  custom_prompts:
    - "Focus on MVP feature implementation"
    - "Ensure proper error handling"
    - "Check for security best practices"
    - "Verify responsive design"
    - "Validate TypeScript types" 