
// This file is automatically generated, do not edit manually
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      compliance_rules: {
        Row: {
          active: boolean | null
          condition_logic: string
          created_at: string | null
          description: string | null
          group_name: string
          id: string
          name: string
          priority: number | null
          required_documents: Json
        }
        Insert: {
          active?: boolean | null
          condition_logic: string
          created_at?: string | null
          description?: string | null
          group_name: string
          id?: string
          name: string
          priority?: number | null
          required_documents: Json
        }
        Update: {
          active?: boolean | null
          condition_logic?: string
          created_at?: string | null
          description?: string | null
          group_name?: string
          id?: string
          name?: string
          priority?: number | null
          required_documents?: Json
        }
        Relationships: []
      }
      compliance_task_templates: {
        Row: {
          created_at: string | null
          days_from_start: number | null
          description: string | null
          id: string
          is_recurring: boolean | null
          recurring_interval: string | null
          title: string
          visa_type: Database["public"]["Enums"]["visa_type"]
        }
        Insert: {
          created_at?: string | null
          days_from_start?: number | null
          description?: string | null
          id?: string
          is_recurring?: boolean | null
          recurring_interval?: string | null
          title: string
          visa_type: Database["public"]["Enums"]["visa_type"]
        }
        Update: {
          created_at?: string | null
          days_from_start?: number | null
          description?: string | null
          id?: string
          is_recurring?: boolean | null
          recurring_interval?: string | null
          title?: string
          visa_type?: Database["public"]["Enums"]["visa_type"]
        }
        Relationships: []
      }
      compliance_tasks: {
        Row: {
          category: string | null
          created_at: string | null
          description: string | null
          due_date: string | null
          id: string
          is_completed: boolean | null
          phase: string | null
          priority: string | null
          title: string
          updated_at: string | null
          user_id: string
          visa_type: Database["public"]["Enums"]["visa_type"] | null
        }
        Insert: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          is_completed?: boolean | null
          phase?: string | null
          priority?: string | null
          title: string
          updated_at?: string | null
          user_id: string
          visa_type?: Database["public"]["Enums"]["visa_type"] | null
        }
        Update: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          is_completed?: boolean | null
          phase?: string | null
          priority?: string | null
          title?: string
          updated_at?: string | null
          user_id?: string
          visa_type?: Database["public"]["Enums"]["visa_type"] | null
        }
        Relationships: []
      }
      documents: {
        Row: {
          category: string
          created_at: string | null
          file_type: string | null
          file_url: string
          id: string
          is_required: boolean | null
          title: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          category: string
          created_at?: string | null
          file_type?: string | null
          file_url: string
          id?: string
          is_required?: boolean | null
          title: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          category?: string
          created_at?: string | null
          file_type?: string | null
          file_url?: string
          id?: string
          is_required?: boolean | null
          title?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      dso_profiles: {
        Row: {
          contact_email: string | null
          contact_phone: string | null
          created_at: string | null
          department: string | null
          id: string
          office_hours: string | null
          office_location: string | null
          role: Database["public"]["Enums"]["dso_role"] | null
          title: string | null
          university_id: string | null
          updated_at: string | null
        }
        Insert: {
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string | null
          department?: string | null
          id: string
          office_hours?: string | null
          office_location?: string | null
          role?: Database["public"]["Enums"]["dso_role"] | null
          title?: string | null
          university_id?: string | null
          updated_at?: string | null
        }
        Update: {
          contact_email?: string | null
          contact_phone?: string | null
          created_at?: string | null
          department?: string | null
          id?: string
          office_hours?: string | null
          office_location?: string | null
          role?: Database["public"]["Enums"]["dso_role"] | null
          title?: string | null
          university_id?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          address: string | null
          country: string | null
          course_start_date: string | null
          created_at: string | null
          date_of_birth: string | null
          degree_level: string | null
          email: string | null
          employment_start_date: string | null
          field_of_study: string | null
          id: string
          is_stem: boolean | null
          name: string | null
          onboarding_complete: boolean | null
          passport_expiry_date: string | null
          passport_number: string | null
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          university: string | null
          university_id: string | null
          updated_at: string | null
          us_entry_date: string | null
          visa_type: Database["public"]["Enums"]["visa_type"] | null
        }
        Insert: {
          address?: string | null
          country?: string | null
          course_start_date?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          degree_level?: string | null
          email?: string | null
          employment_start_date?: string | null
          field_of_study?: string | null
          id: string
          is_stem?: boolean | null
          name?: string | null
          onboarding_complete?: boolean | null
          passport_expiry_date?: string | null
          passport_number?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          university?: string | null
          university_id?: string | null
          updated_at?: string | null
          us_entry_date?: string | null
          visa_type?: Database["public"]["Enums"]["visa_type"] | null
        }
        Update: {
          address?: string | null
          country?: string | null
          course_start_date?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          degree_level?: string | null
          email?: string | null
          employment_start_date?: string | null
          field_of_study?: string | null
          id?: string
          is_stem?: boolean | null
          name?: string | null
          onboarding_complete?: boolean | null
          passport_expiry_date?: string | null
          passport_number?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          university?: string | null
          university_id?: string | null
          updated_at?: string | null
          us_entry_date?: string | null
          visa_type?: Database["public"]["Enums"]["visa_type"] | null
        }
        Relationships: []
      }
      universities: {
        Row: {
          country: string
          created_at: string | null
          id: string
          name: string
          sevis_id: string | null
          updated_at: string | null
          website: string | null
        }
        Insert: {
          country: string
          created_at?: string | null
          id?: string
          name: string
          sevis_id?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Update: {
          country?: string
          created_at?: string | null
          id?: string
          name?: string
          sevis_id?: string | null
          updated_at?: string | null
          website?: string | null
        }
        Relationships: []
      }
      university_configs: {
        Row: {
          created_at: string | null
          id: string
          updated_at: string | null
          visa_types_supported: string[] | null
        }
        Insert: {
          created_at?: string | null
          id: string
          updated_at?: string | null
          visa_types_supported?: string[] | null
        }
        Update: {
          created_at?: string | null
          id?: string
          updated_at?: string | null
          visa_types_supported?: string[] | null
        }
        Relationships: [
          {
            foreignKeyName: "university_configs_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "universities"
            referencedColumns: ["id"]
          }
        ]
      }
      university_document_rules: {
        Row: {
          created_at: string | null
          document_requirements: Json
          id: string
          university_id: string
          updated_at: string | null
          visa_type: string
        }
        Insert: {
          created_at?: string | null
          document_requirements: Json
          id?: string
          university_id: string
          updated_at?: string | null
          visa_type: string
        }
        Update: {
          created_at?: string | null
          document_requirements?: Json
          id?: string
          university_id?: string
          updated_at?: string | null
          visa_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "university_document_rules_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          }
        ]
      }
      university_join_requests: {
        Row: {
          created_at: string | null
          id: string
          requested_role: Database["public"]["Enums"]["dso_role"]
          status: string
          university_id: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          requested_role?: Database["public"]["Enums"]["dso_role"]
          status?: string
          university_id?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          requested_role?: Database["public"]["Enums"]["dso_role"]
          status?: string
          university_id?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "university_join_requests_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "university_join_requests_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      dso_role: "dso_admin" | "dso_viewer"
      user_role: "student" | "dso" | "admin"
      visa_type: "F1" | "J1" | "H1B" | "CPT" | "OPT" | "STEM_OPT" | "Other"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
