name: CodeRabbit Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  coderabbit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run linting
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: CodeRabbit Review
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODERABBIT_API_KEY: ${{ secrets.cr-25e9b6eb057dec94f1632ae671e4bf350330363255cbf0b2fa85c2c765 }}
        with:
          # Configuration options
          review_comment_lgtm: true
          path_filters: |
            src/**
            *.{ts,tsx,js,jsx}
            *.{json,yaml,yml}
            *.{md,txt}
          ignore_files: |
            node_modules/**
            dist/**
            build/**
            *.min.js
            *.bundle.js
            coverage/**
            *.test.{ts,tsx,js,jsx}
            *.spec.{ts,tsx,js,jsx}

      - name: Security Scan
        uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'

      - name: Performance Check
        run: |
          echo "Running performance checks..."
          npm run build
          echo "Bundle size analysis completed"

      - name: Accessibility Check
        run: |
          echo "Running accessibility checks..."
          # Add accessibility testing commands here
          echo "Accessibility checks completed"

      - name: MVP Feature Compliance Check
        run: |
          echo "Checking MVP feature compliance..."
          # Add MVP-specific checks here
          echo "MVP compliance check completed" 